### ISSUE TITLE
prismarineChunkToNbt receiving undefined chunk

### ISSUE THREAD

**Issue by kf106** [PrismarineJS/prismarine-provider-anvil#63]
https://github.com/PrismarineJS/flying-squid/issues/566

When flying squid has to load many chunks in one go, often the error below occurs:

```
              Biomes: { value: chunk.biomes, type: 'intArray' },
                                     ^

TypeError: Cannot read properties of undefined (reading 'biomes')
    at prismarineChunkToNbt (/home/kf106/prismarine/flying-squid/node_modules/prismarine-provider-anvil/src/1.14/chunk.js:25:38)
    at Anvil.save (/home/kf106/prismarine/flying-squid/node_modules/prismarine-provider-anvil/src/anvil.js:44:19)
    at World.saveNow (/home/kf106/prismarine/flying-squid/node_modules/prismarine-world/src/world.js:139:30)
    at Timeout._onTimeout (/home/kf106/prismarine/flying-squid/node_modules/prismarine-world/src/world.js:147:18)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

```

chunk has no Biomes or Section keys.

 I'm guessing that this is due to the generator function not producing the chunks fast enough and some kind of async problem.

**Comment by kf106** [comment]
Tracked the problem back to this function in prismarine-world/scr/world.js so far - there are empty entries in savingQueue that cause prismarineChunkToNbt to fail due to receiving an undefined chunk:
```
  async saveNow () {
    if (this.savingQueue.size === 0) {
      return
    }
    // We could set a limit on the number of chunks to save at each
    // interval. The set structure is maintaining the order of insertion
    for (const [key, { chunkX, chunkZ }] of this.savingQueue.entries()) {
      if (!(typeof this.columns[key] === 'undefined')) {
      this.finishedSaving = Promise.all([this.finishedSaving,
        this.storageProvider.save(chunkX, chunkZ, this.columns[key])])
      } else { console.log("Trying to save undefined column") }
    }
    this.savingQueue.clear()
    this.emit('doneSaving')
  }
```

This is a "fix" but really the reason why null entries are being written to savingQueue should be determined

**Comment by kf106** [comment]
Unfortunately this just pushes the problem further upstream: 

```
May 20th 2022, 09:00:29 [ERROR]: Client ::ffff:127.0.0.1:53052 : TypeError: Serialization error for play.toClient : SizeOf error for undefined : Cannot read properties of undefined (reading 'length')
    at eval (eval at compile (/home/prismarine/flying-squid/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1049:39)
    at eval (eval at compile (/home/prismarine/flying-squid/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1053:13)
    at Object.packet_map_chunk (eval at compile (/home/prismarine/flying-squid/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1056:9)
    at eval (eval at compile (/home/prismarine/flying-squid/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2272:58)
    at packet (eval at compile (/home/prismarine/flying-squid/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2330:9)
    at CompiledProtodef.sizeOf (/home/prismarine/flying-squid/node_modules/protodef/src/compiler.js:89:14)
    at e.message (/home/prismarine/flying-squid/node_modules/protodef/src/compiler.js:96:40)
    at tryCatch (/home/prismarine/flying-squid/node_modules/protodef/src/utils.js:50:16)
    at CompiledProtodef.createPacketBuffer (/home/prismarine/flying-squid/node_modules/protodef/src/compiler.js:96:20)
    at Serializer.createPacketBuffer (/home/prismarine/flying-squid/node_modules/protodef/src/serializer.js:12:23)
May 20th 2022, 09:00:29 [INFO]: eric disconnected
```

**Comment by kf106** [comment]
So it looks like this is a prismarine-world problem in handling async, with columns being requested and then passed on before they have been resolved. I'm now pretty sure that the problem is with generation not creating the chunk in time for prismarine-world.

**Comment by rom1504** [comment]
just means the wrong chunk are saved

**Comment by kf106** [comment]
Can you elaborate, @rom1504?

**Comment by kf106** [comment]
prismarine-world should not be handing null chunks to prismarine-provider-anvil. A check in the latter whether that has happened doesn't fix it, because the null chunk is being passed elsewhere.

So I'm now stuck at why prismarine-world is passing null chunks - are they not getting created in time or not at all, and where is it passing them on to besides prismarine-provider-anvil...

**Comment by kf106** [comment]
prismarine-world/src/world.js line 94: https://github.com/PrismarineJS/prismarine-world/blob/a5747ba466c0a77413e2b117337763debc9688cd/src/world.js#L94

Should there be an await in front of that to give the generator time? (Although I tried it, and it didn't fix the problem)

**Comment by kf106** [comment]
@rom1504 - I put some debug messages in to indicate when a chunk was being read from file, and when from the generator. The latest error happens when reading from file:

```
3|flying-squid  | Getting chunk from generator
3|flying-squid  | > 
Getting chunk from file
3|flying-squid  | > 
3|flying-squid  | 
May 21st 2022, 13:34:13 [ERROR]: Client ::ffff:127.0.0.1:45182 : TypeError: Serialization error for play.toClient : SizeOf error for undefined : Cannot read properties of undefined (reading 'length')
3|flying-squid  |     at eval (eval at compile (/home/ropsten/PICT-infinite/orthoverse-prismarine/flying-squid/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1049:39)
3|flying-squid  |     at eval (eval at compile (/home/ropsten/PICT-infinite/orthoverse-prismarine/flying-squid/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1053:13)
3|flying-squid  |     at Object.packet_map_chunk (eval at compile (/home/ropsten/PICT-infinite/orthoverse-prismarine/flying-squid/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1056:9)
3|flying-squid  |     at eval (eval at compile (/home/ropsten/PICT-infinite/orthoverse-prismarine/flying-squid/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2272:58)
3|flying-squid  |     at packet (eval at compile (/home/ropsten/PICT-infinite/orthoverse-prismarine/flying-squid/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2330:9)
3|flying-squid  |     at CompiledProtodef.sizeOf (/home/ropsten/PICT-infinite/orthoverse-prismarine/flying-squid/node_modules/protodef/src/compiler.js:89:14)
3|flying-squid  |     at e.message (/home/ropsten/PICT-infinite/orthoverse-prismarine/flying-squid/node_modules/protodef/src/compiler.js:96:40)
3|flying-squid  |     at tryCatch (/home/ropsten/PICT-infinite/orthoverse-prismarine/flying-squid/node_modules/protodef/src/utils.js:50:16)
3|flying-squid  |     at CompiledProtodef.createPacketBuffer (/home/ropsten/PICT-infinite/orthoverse-prismarine/flying-squid/node_modules/protodef/src/compiler.js:96:20)
3|flying-squid  |     at Serializer.createPacketBuffer (/home/ropsten/PICT-infinite/orthoverse-prismarine/flying-squid/node_modules/protodef/src/serializer.js:12:23)
3|flying-squid  | > 
3|flying-squid  | 
May 21st 2022, 13:34:13 [INFO]: eric disconnected
3|flying-squid  | > 
3|flying-squid  | 
3|flying-squid  | Getting chunk from file
3|flying-squid  | > 
Getting chunk from file
3|flying-squid  | > 
Getting chunk from file
3|flying-squid  | > 
Getting chunk from file
3|flying-squid  | > 
Getting chunk from file

```

What do you think is going wrong? File not yet written but attempt to read and send? Or null value written to file? Or attempting to send to client before file read?

**Comment by kf106** [comment]
Given that the server is running, I tried reconnecting, and got exactly the same error, at the same point, when reading the first chunk from file. I'm still thinking about what this means.

**Comment by kf106** [comment]
Okay, so disabling reading chunks from file by commenting out line 90 https://github.com/PrismarineJS/prismarine-world/blob/a5747ba466c0a77413e2b117337763debc9688cd/src/world.js#L90 of the prismarine-world/src/world.js suppressed the error. From this I conclude that it's not the generator, but rather a file read/write problem. Well, that's progress. At least for a demo I can use this, but of course any changes made to the world are lost once columns are unloaded...

**Comment by kf106** [comment]
I started to monitor the size of this.savingQueue to see if there's an upper limit where it happens. Sometimes the queue gets up to 80 or 90, but then clears fine. It also doesn't seem to be related to how many columns have been written to file - sometimes the crash happens after 60 or 80, other times is 300 to 400 that have been saved.

**Comment by kf106** [comment]
I think I have made some progress. I put in some debug statements. Looks like columns are being unloaded before they are saved, hence they are saved as null, and when you return to the area there is an attempt to load that null chunk resulting from the null column, and it crashes:
```
Unloading 1,7 at world.js:126
Unloading 6,2 at world.js:126
...
Unloading -5,7 at world.js:126
Unloading 6,-4 at world.js:126
Null column at prismarine-world/src/world.js:138 with key 1,7

```

**Comment by kf106** [comment]
Yep, if I check in unloadColumn whether I'm trying to unload a column in the save queue and don't unload such columns, I can't get it to crash anymore.

  unloadColumn (chunkX, chunkZ) {
    console.log("Unloading " + chunkX.toString() + "," + chunkZ.toString() + " at world.js:126")
    const key = columnKeyXZ(chunkX, chunkZ)
    if (this.savingQueue.has(columnKeyXZ(chunkX, chunkZ))) {
      console.log("Tried to unload pending save column")
    } else {
    delete this.columns[key]
    const columnCorner = new Vec3(chunkX * 16, 0, chunkZ * 16)
    this.emit('chunkColumnUnload', columnCorner)
    }
  }
  
  https://github.com/PrismarineJS/prismarine-world/blob/a5747ba466c0a77413e2b117337763debc9688cd/src/world.js#L124
